[General]
# Whether to run the app on windows startup or not.
RunAtStartup=true

# These options are for the base taskbar state
[Regular]
# Taskbar Tint color, This is in hexadecimal notation ex: #7289DA
# It can also contain opacity(alpha) ex: #BF7289DA => {BF equals 75% opacity}
# for more info about hexdecimal color opacity, check this https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
Color="#00000000"

# Can be one of  (normal, transparent, blur, fluent, opaque)
AccentState="transparent"

# Rules define how this taskbar state changes according to active window (Only  for Regular and MaximizedWindow states)
#
# Each rule consists of exe name (should be all lowercase) and the hex color (can contain opacity/alpha values)
#
# Note:- notice the quotes around the two sides of the rule
#
# Rule syntax:
#   "exename"="color/accentState".
# Example:
#   [Regular.Rules]
#   "cmd.exe"="#202225/opaque"
#   "discord.exe"="#202225/opaque"
[Regular.Rules]
# "cmd.exe"="#202225/opaque"
# "discord.exe"="#202225/opaque"


# These options are for when there is a Maximized Window open
[MaximizedWindow]
Color="#1F1F1F"
AccentState="opaque"

[MaximizedWindow.Rules]
"cmd.exe"="#202225/opaque"
"discord.exe"="#202225/opaque"


# These options are for when The TaskView is open
[TaskViewOpen]
Color="#1F1F1F"
AccentState="transparent"